### ISSUE TITLE
Possible polishing for Logistic Regressor

### ISSUE THREAD

**Issue by snowthesprite** [charliebrown364/machine-learning#14]
I have.... several things. All of them are minor, but they'll shorten your code by a lot.

_**I know this looks like an essay but I just ramble and explain every change cause I'm just weird that way. Ya could probably finish this in like 2 minutes, its a lot of deleting and a little renaming/rephrasing**_

Starting with just minor cleaning up (there's not a lot don't worry) top to bottom. First, you don't need to state all of the 'src' stuff because you're in the src folder, ya can just delete it. So with your `ln(x)`, you don't actually really need any of it. `math.log(x)` is already base e. You can keep the function and if you want, but you don't need all that in the return. Next you could remove all the `new_dict` stuff in your predict function. I don't think you use it anyway. 

The more major section is child classes. I've probably said this to several people at this point, but I think it would work especially well for you cause.... you're sorta already doing it. We looked at these earlier in the year, but it was a while ago and we only really touched on them for like an assignment or two. So a child class is a kind of class that will inherit all of the functions of its parent class; you don't have to restate them. You can declare a class a child class by doing this :
```
class  LogisticRegressor (LinearRegressor) :
```
Now the Logistic Regressor has access to all of the Linear Regressors functions. Now you can completely delete all of the Linear Regressor things in your calculate_coefficients, ya don't need them anymore. Next you need to rename your calc coefficents, cause if you don't it'll overwrite the function name, then call the function before you call your normal calc_coefficents. Now you pretty much have your renamed function and your predict. You could get rid of your predict function by adding one attribute to both your Linear and Logistic init functions, which would pass the results of the predict through a lambda equation that would return it untouched in the linear regressor and pass it through the `upper bound/ 1 + e` thing in your Logistic regressor. Now ya don't need the predict function and you'll only have like 22 lines of code.

The nice thing about child classes is that whatever you do to the parent happens in the child too. So if you want to change something in the predict (like the interaction term stuff), it'll carry over _without_ you having to make a new object every time you run the function.

**Comment by charliebrown364** [comment]
I did the smaller stuff, but when we first started with the logistic regressor, I asked justin if we could just make the logistic regressor a child class of the linear regressor, and he said something against that idea. Since I don't use those regressors much anymore, I'll not make my logistic regressor a child class. Thanks for the suggestion, though.
