### ISSUE TITLE
Comment for src/matrix.py

### ISSUE THREAD

**Issue by JHpusd** [charliebrown364/machine-learning#4]
This is completely trivial, since there is no hard error, but I would recommend you overload your matrix operators by simply changing the name of the class method. Using the matrix subtraction as an example:
Instead of
def mat_sub(...):
\ \ \ \ (code here)
def \_\_sub\_\_(...):
\ \ \ \ return self.mat_sub(...)

simply just change your mat_sub method to
def \_\_sub\_\_(...):
\ \ \ \ (code here)

Again, this is just a recommendation to make your code more compact.

**Comment by charliebrown364** [comment]
I could do that, but I like it the way I have it right now.
